version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:14.7-bullseye
    ports:
      - 5435:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always